server:
  error:
    path: error
  servlet:
    session:
      cookie:
        name: SCTP-JSESSIONID
  port: 8282
  host: localhost

auth:
  max_attempts: 3
  jwt:
    iss: sctp-mis

logging:
  level:
    org:
      cga: WARN
    root: ERROR

spring:
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  application:
    name: "SCTP MIS"
    version: @project.version@
    build_timestamp: @maven.build.timestamp@
  mvc:
    logResolvedException: false
  datasource:
    username:
    password:
    url: jdbc:mysql://
  flyway:
    locations: classpath:db/migration,classpath:db/callback
    out-of-order: true
    baselineOnMigrate: true

# Pebble configuration
pebble:
  prefix: templates # Look for templates is /resources/templates (Under class path)
  suffix: .peb # Extension of template files
  exposeRequestAttributes: true

# Email/SMTP settings
simplejavamail:
  transportstrategy: SMTP
  fromName: SCTP MIS
  fromAddress: no-reply@sctp.localhost.com
  smtp:
    host: localhost
    port: 25
    password:
    username:
  javaxmail:
    debug: false