spring:
  config:
    import: classpath:sctp-common.yaml

#
# Create new document so to allow overriding of properties
---
spring:
  application:
    name: "SCTP MIS"
    version: @project.version@
    build_timestamp: @maven.build.timestamp@
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    path: error
  servlet:
    session:
      cookie:
        name: SCTP-JSESSIONID
  port: 8282
  host: localhost
  # forward-headers-strategy: native # Enable if behind proxy to have spring boot grab ip/scheme(port) details from headers
  #host_info: # override if behind a proxy
  #  host: localhost
  #  port: 43
  #  ssl_on: true

auth:
  jwt:
    iss: sctp-mis

logging:
  level:
    org:
      cga: ERROR
    root: ERROR

# Pebble configuration
pebble:
  prefix: templates # Look for templates is /resources/templates (Under class path)
  suffix: .peb # Extension of template files
  exposeRequestAttributes: true

# TUS File Upload (These files are temporary)
tus:
  server:
    upload:
      limit: 400MB # Maximum upload size
    data:
      directory: ${java.io.tmpdir}/tus

# File import staging directory
# When a file has been uploaded, it will be moved here from the temporary directory.
imports:
  staging: ./staging

# Targeting related settings
targeting:
  pictures: ./beneficiary-images # Where to save beneficiary pictures. If the directory does not exist, it will be created.

sctp:
  transfers:
    # Number of months in a transfer period for manual transfers, defaults to 2
    manualTransferFrequency: 2
