spring:
  config:
    import: classpath:sctp-common.yaml
#
# Overriding imports only works when you start a new document
#
---

spring:
  jpa:
    properties:
      hibernate:
        order_updates: true
        jdbc:
          batch_size: 100
        proc:
          param_null_passing: true
  application:
    name: "SCTP API"
    version: @project.version@
    build_timestamp: @maven.build.timestamp@
springfox:
  documentation:
    swagger:
      use-model-v3: false
server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  servlet:
    context-path: "/"
  port: 8383

# Authentication
auth:
  jwt:
    iss: sctp-api
    secret: # Must be at least 256bits (32 characters)
    expiration: 43200 # In minutes

# Logging level
logging:
  level:
    org:
      cga: INFO
    root: WARN

# Spring Doc + API documentation configuration (/api-doc.yaml or /api-doc)
springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /api-doc
    enabled: false
  swagger-ui:
    doc-expansion: none
    enabled: false