spring:
  config:
    import: file:../sctp-common-local.yaml

---
# Logging level
logging:
  level:
    org:
      cga: INFO
    root: ERROR

auth:
  max_attempts: 3

spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://localhost/sctp


# Email/SMTP settings
simplejavamail:
  fromAddress: no-reply@sctp.localhost.com
  smtp:
    host: localhost
    port: 25
    password:
    username: